services:
  angular:
    build: .
    container_name: siteperso-angular-1
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - web-network

networks:
  web-network:
    external: true
